### ISSUE TITLE
[octref.vetur] Error: @types/vscode ^1.43.0 greater than engines.vscode ^1.42.0. Consider upgrade engines.vscode or use an older @types/vscode version

### ISSUE THREAD

**Issue by jankeromnes** [open-vsx/publish-extensions#10]
```
[FAIL] Could not process extension: {
  "id": "octref.vetur",
  "version": "0.24.0",
  "repository": "https://github.com/vuejs/vetur"
}
Error: @types/vscode ^1.43.0 greater than engines.vscode ^1.42.0. Consider upgrade engines.vscode or use an older @types/vscode version
    at Object.validateVSCodeTypesCompatibility (/home/runner/work/publish-extensions/publish-extensions/node_modules/vsce/out/validation.js:85:19)
    at validateManifest (/home/runner/work/publish-extensions/publish-extensions/node_modules/vsce/out/package.js:551:22)
    at async Promise.all (index 0)
```

**Comment by jankeromnes** [comment]
Seems to have worked? https://open-vsx.org/extension/octref/vetur

Also I can't find the corresponding GitHub Actions Workflow.
