### ISSUE TITLE
[zhuangtongfa.material-theme] Cannot find module './editorTheme/oneDarkPro'

### ISSUE THREAD

**Issue by jankeromnes** [open-vsx/publish-extensions#12]
```
Running: npm install
🚀  Created namespace zhuangtongfa
Executing prepublish script 'npm run vscode:prepublish'...
[FAIL] Could not process extension: {
  "id": "zhuangtongfa.material-theme",
  "version": "3.2.4",
  "repository": "https://github.com/Binaryify/OneDark-Pro"
}
Error: Command failed: npm run vscode:prepublish
warning material-theme@3.2.4: The engine "vscode" appears to be invalid.
warning material-theme@3.2.4: The engine "vscode" appears to be invalid.

/tmp/repository/node_modules/ts-node/src/index.ts:421
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
##[error]src/themes/editor.ts(7,24): error TS2307: Cannot find module './editorTheme/oneDarkPro'.

    at createTSError (/tmp/repository/node_modules/ts-node/src/index.ts:421:12)
    at reportTSError (/tmp/repository/node_modules/ts-node/src/index.ts:425:19)
    at getOutput (/tmp/repository/node_modules/ts-node/src/index.ts:557:36)
    at Object.compile (/tmp/repository/node_modules/ts-node/src/index.ts:762:32)
    at Module.m._compile (/tmp/repository/node_modules/ts-node/src/index.ts:841:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Object.require.extensions.<computed> [as .ts] (/tmp/repository/node_modules/ts-node/src/index.ts:844:12)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
error Command failed with exit code 1.
error Command failed with exit code 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! material-theme@3.2.4 vscode:prepublish: `yarn compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the material-theme@3.2.4 vscode:prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-03-20T11_11_32_460Z-debug.log

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:311:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm run vscode:prepublish'
}
##[error]Process completed with exit code 255.
```

**Comment by jankeromnes** [comment]
So first of all, the first line shouldn't be `npm install` but `yarn install`, because https://github.com/Binaryify/OneDark-Pro has a `yarn.lock` file.

**Comment by jankeromnes** [comment]
Fixed: https://open-vsx.org/extension/zhuangtongfa/material-theme
