### ISSUE TITLE
[ms-azuretools.vscode-docker][ms-mssql.mssql][ms-vscode.powershell-preview] Error: Cannot resolve dependency

### ISSUE THREAD

**Issue by jankeromnes** [open-vsx/publish-extensions#13]
## ms-azuretools.vscode-docker

```
Executing prepublish script 'npm run vscode:prepublish'...
clean-webpack-plugin: /tmp/repository/dist has been removed.

⚠ ｢copy-webpack-plugin｣: unable to locate 'out/src/utils/getCoreNodeModule.js' at '/tmp/repository/out/src/utils/getCoreNodeModule.js'
> vscode-docker@1.0.0 vscode:prepublish /tmp/repository
> npm run webpack-prod


> vscode-docker@1.0.0 webpack-prod /tmp/repository
> gulp webpack-prod

[15:14:38] Requiring external module ts-node/register
[15:14:40] Using gulpfile /tmp/repository/gulpfile.ts
[15:14:40] Starting 'webpack-prod'...
External node modules: [ 'vscode-languageclient', 'opn' ]
Excluded node modules (external node modules plus dependencies) [
  'is-wsl',
  'opn',
  'semver',
  'vscode-jsonrpc',
  'vscode-languageclient',
  'vscode-languageserver-protocol',
  'vscode-languageserver-types'
]
   2544 modules

WARNING in ./node_modules/websocket/lib/BufferUtil.js
Module not found: Error: Can't resolve '../build/Release/bufferutil' in '/tmp/repository/node_modules/websocket/lib'

WARNING in ./node_modules/websocket/lib/Validation.js
Module not found: Error: Can't resolve '../build/Release/validation' in '/tmp/repository/node_modules/websocket/lib'

WARNING in ./node_modules/websocket/lib/BufferUtil.js
Module not found: Error: Can't resolve '../build/default/bufferutil' in '/tmp/repository/node_modules/websocket/lib'

WARNING in ./node_modules/websocket/lib/Validation.js
Module not found: Error: Can't resolve '../build/default/validation' in '/tmp/repository/node_modules/websocket/lib'

WARNING in ./node_modules/applicationinsights/out/AutoCollection/NativePerformance.js
Module not found: Error: Can't resolve 'applicationinsights-native-metrics' in '/tmp/repository/node_modules/applicationinsights/out/AutoCollection'

WARNING in unable to locate 'out/src/utils/getCoreNodeModule.js' at '/tmp/repository/out/src/utils/getCoreNodeModule.js'
[Error: ENOENT: no such file or directory, lstat '/tmp/repository/out/test'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/tmp/repository/out/test'
}
[15:16:08] Finished 'webpack-prod' after 1.47 min
 DONE  Packaged: /tmp/tmp-34028JnXZK4SYRqq.vsix (185 files, 1.57MB)

[FAIL] Could not process extension: {
  "id": "ms-azuretools.vscode-docker",
  "version": "1.0.0",
  "repository": "https://github.com/microsoft/vscode-docker",
  "checkout": "v1.0.0"
}
Error: Cannot resolve dependency: vscode.docker
    at Object.<anonymous> (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/publish.js:52:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/publish.js:14:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## ms-mssql.mssql

```
This extension consists of 2516 files, out of which 2091 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore
 DONE  Packaged: /tmp/tmp-3402vy35W0kgc7v8.vsix (2516 files, 2.84MB)

[FAIL] Could not process extension: {
  "id": "ms-mssql.mssql",
  "version": "1.9.0",
  "repository": "https://github.com/Microsoft/vscode-mssql"
}
Error: Cannot resolve dependency: vscode.sql
    at Object.<anonymous> (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/publish.js:52:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/publish.js:14:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by jankeromnes** [comment]
### ms-vscode.powershell-preview

```
This extension consists of 559 files, out of which 326 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore
 DONE  Packaged: /tmp/tmp-340217C0q3j6m439.vsix (559 files, 845.99KB)

[FAIL] Could not process extension: {
  "id": "ms-vscode.powershell-preview",
  "version": "2020.3.0",
  "repository": "https://github.com/PowerShell/vscode-powershell"
}
Error: Cannot resolve dependency: vscode.powershell
    at Object.<anonymous> (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/publish.js:52:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/publish.js:14:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by jankeromnes** [comment]
Updates:

- Namespace `ms-azuretools` has since been claimed: https://github.com/eclipse/open-vsx.org/issues/5

- `ms-mssql.mssql` and `ms-vscode.powershell-preview` were published successfully in https://github.com/open-vsx/publish-extensions/runs/523496238:

```
🚀  Published ms-mssql.mssql v1.9.0
[OK] Successfully published ms-mssql.mssql to Open VSX!
```

```
🚀  Published ms-vscode.powershell-preview v2020.3.0
[OK] Successfully published ms-vscode.powershell-preview to Open VSX!
```
