### ISSUE TITLE
[Ikuyadeu.r] SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by jankeromnes** [open-vsx/publish-extensions#14]
```
[FAIL] Could not process extension: {
  "id": "Ikuyadeu.r",
  "version": "1.2.7",
  "repository": "https://github.com/Ikuyadeu/vscode-R"
}
Error: Command failed: npm run vscode:prepublish
/tmp/repository/webpack.config.js:5
import { resolve as _resolve } from 'path';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (vm.js:88:7)
    at NativeCompileCache._moduleCompile (/tmp/repository/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/tmp/repository/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (/tmp/repository/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/tmp/repository/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/tmp/repository/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /tmp/repository/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/tmp/repository/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at /tmp/repository/node_modules/webpack-cli/bin/cli.js:71:45
    at Object.parse (/tmp/repository/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
```

**Comment by jankeromnes** [comment]
This seems to have been fixed upstream, because publishing works now:

> 🚀  Published Ikuyadeu.r v1.2.7
> [OK] Successfully published Ikuyadeu.r to Open VSX!
