### ISSUE TITLE
[ms-vscode.node-debug] The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by spoenemann** [open-vsx/publish-extensions#20]
```
Error: Command failed: yarn install
Running: rm -rf /tmp/repository
warning node-debug@1.35.3: The engine "vscode" appears to be invalid.
error node-debug@1.35.3: The engine "node" is incompatible with this module. Expected version "^10.2.0". Got "12.16.1"
error Found incompatible module.

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:311:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

**Comment by akosyakov** [comment]
fyi Theia is still using Node.js to run VS Code extensions and node debug adapters, it does not make sense to use LTE to build them

**Comment by spoenemann** [comment]
Ok let's switch to Node 10.x

**Comment by jankeromnes** [comment]
Ok, since Node.js v10 still has status "Active LTS", and still has until `2021-04-30` before reaching end-of-life, it seems acceptable to use the older version here.

Source: https://nodejs.org/en/about/releases/
