### ISSUE TITLE
[rebornix.ruby]  npm ERR! 404 Not Found - GET https://registry.npmjs.org/language-server-ruby - Not found

### ISSUE THREAD

**Issue by jankeromnes** [open-vsx/publish-extensions#23]
https://github.com/open-vsx/publish-extensions/runs/567512213:

```
Attempting to publish rebornix.ruby to Open VSX
Running: git clone https://github.com/rubyide/vscode-ruby /tmp/repository
Running: git checkout v0.27.0
Running: npm install
[FAIL] Could not process extension: {
  "id": "rebornix.ruby",
  "version": "0.27.0",
  "repository": "https://github.com/rubyide/vscode-ruby",
  "checkout": "v0.27.0",
  "location": "packages/vscode-ruby-client"
}
{ Error: Command failed: npm install
npm WARN deprecated @types/execa@2.0.0: This is a stub types definition. execa provides its own type definitions, so you do not need this installed.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/language-server-ruby - Not found
npm ERR! 404 
npm ERR! 404  'language-server-ruby@^0.27.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'vscode-ruby-client'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-04-07T12_32_36_803Z-debug.log
```

**Comment by jankeromnes** [comment]
Publishing of `rebornix.ruby` should be fixed by https://github.com/open-vsx/publish-extensions/pull/31.

In the latest run, it still failed with:

```
[FAIL] Could not process extension: {
  "id": "rebornix.ruby",
  "version": "0.27.0",
  "repository": "https://github.com/rubyide/vscode-ruby",
  "checkout": "v0.27.0",
  "location": "packages/vscode-ruby-client"
}
Error: Cannot resolve dependency: wingrunr21.vscode-ruby
    at Object.<anonymous> (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/publish.js:52:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/publish.js:14:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Running: rm -rf /tmp/repository
Extension not found: wingrunr21.vscode-ruby
```

but that's expected, because that dependency only got published right after that:

```
Processing extension: {
  "id": "wingrunr21.vscode-ruby",
  "version": "0.27.0",
  "repository": "https://github.com/rubyide/vscode-ruby",
  "checkout": "v0.27.0",
  "location": "packages/vscode-ruby"
}
Checking Open VSX version of wingrunr21.vscode-ruby
Attempting to publish wingrunr21.vscode-ruby to Open VSX
Running: git clone https://github.com/rubyide/vscode-ruby /tmp/repository
Running: git checkout v0.27.0
Running: yarn install
🚀  Created namespace wingrunr21
 WARNING  The 'extensionKind' property should be of type 'string[]'. Learn more at: https://aka.ms/vscode/api/incorrect-execution-location
 DONE  Packaged: /tmp/tmp-26637hdqy5SlDti5.vsix (18 files, 59.08KB)

🚀  Published wingrunr21.vscode-ruby v0.27.0
[OK] Successfully published wingrunr21.vscode-ruby to Open VSX!
```

Since the second extension was published successfully, I expect `rebornix.ruby` to also get published successfully on the next CI run.

**Comment by jankeromnes** [comment]
Indeed, `rebornix.ruby` is now successfully published! 🎉 https://open-vsx.org/extension/rebornix/ruby
