### ISSUE TITLE
[christian-kohler.path-intellisense] Error: Images in README.md must come from an HTTPS source

### ISSUE THREAD

**Issue by jankeromnes** [open-vsx/publish-extensions#3]
```
Executing prepublish script 'npm run vscode:prepublish'...

> path-intellisense@1.4.2 vscode:prepublish /tmp/repository
> node ./node_modules/vscode/bin/compile

[FAIL] Could not process extension: {
  "id": "christian-kohler.path-intellisense",
  "version": "1.4.2",
  "repository": "https://github.com/ChristianKohler/PathIntellisense"
}
Error: Images in README.md must come from an HTTPS source: http://i.giphy.com/iaHeUiDeTUZuo.gif
    at Node.<anonymous> (/home/runner/work/publish-extensions/publish-extensions/node_modules/vsce/out/package.js:360:27)
    at initialize.exports.each (/home/runner/work/publish-extensions/publish-extensions/node_modules/cheerio/lib/api/traversing.js:300:24)
    at ReadmeProcessor.<anonymous> (/home/runner/work/publish-extensions/publish-extensions/node_modules/vsce/out/package.js:353:22)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/publish-extensions/publish-extensions/node_modules/vsce/out/package.js:4:58)
```

**Comment by jankeromnes** [comment]
The upstream issue was fixed, and somehow publishing seems to have worked, even though I couldn't find the corresponding GitHub Workflow:

https://open-vsx.org/extension/christian-kohler/path-intellisense
