### ISSUE TITLE
[dsznajder.es7-react-js-snippets] Error: @types/vscode 1.45.1 greater than engines.vscode ^1.45.0. Consider upgrade engines.vscode or use an older @types/vscode version

### ISSUE THREAD

**Issue by jankeromnes** [open-vsx/publish-extensions#38]
```
[FAIL] Could not process extension: {
  "id": "dsznajder.es7-react-js-snippets",
  "version": "2.8.0",
  "repository": "https://github.com/dsznajder/vscode-es7-javascript-react-snippets"
}
Error: @types/vscode 1.45.1 greater than engines.vscode ^1.45.0. Consider upgrade engines.vscode or use an older @types/vscode version
    at Object.validateVSCodeTypesCompatibility (/home/runner/work/publish-extensions/publish-extensions/node_modules/vsce/out/validation.js:85:19)
    at validateManifest (/home/runner/work/publish-extensions/publish-extensions/node_modules/vsce/out/package.js:550:22)
```

**Comment by filiptronicek** [comment]
Looks that this is no longer present after we added this:
https://github.com/open-vsx/publish-extensions/blob/377e1d79b7d0a7d307df34b3ae9f30e86b3ccd2c/publish-extension.js#L53-L54
