### ISSUE TITLE
Jupyter extension timing out on publish

### ISSUE THREAD

**Issue by yimuchen** [open-vsx/publish-extensions#380]
The latest output of the publish extension action for vscode-jupyter

```
Processing extension: {
  "id": "ms-toolsai.jupyter",
  "repository": "https://github.com/microsoft/vscode-jupyter",
  "version": "2021.6.0",
  "checkout": "2021.6.0",
  "prepublish": "PIP_USER=no python3 -m pip --disable-pip-version-check install -t ./pythonFiles/lib/python --no-cache-dir --implementation py --no-deps --upgrade -r requirements.txt && npm run package",
  "extensionFile": "ms-toolsai-jupyter-insiders.vsix"
}
Checking Open VSX version of ms-toolsai.jupyter
Error: Extension not found: ms-toolsai.jupyter
Attempting to publish ms-toolsai.jupyter to Open VSX
    at IncomingMessage.<anonymous> (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/registry.js:176:40)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Warning:  Could not check Open VSX version of ms-toolsai.jupyter
Creating Open VSX namespace failed -- assuming that it already exists
Error: Namespace already exists: ms-toolsai
    at IncomingMessage.<anonymous> (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/registry.js:176:40)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Running: git clone --recurse-submodules https://github.com/microsoft/vscode-jupyter /tmp/repository
Running: git checkout 2021.6.0
Running: npm install
Running: PIP_USER=no python3 -m pip --disable-pip-version-check install -t ./pythonFiles/lib/python --no-cache-dir --implementation py --no-deps --upgrade -r requirements.txt && npm run package
[FAIL] Could not process extension: {
  "id": "ms-toolsai.jupyter",
  "repository": "https://github.com/microsoft/vscode-jupyter",
  "version": "2021.6.0",
  "checkout": "2021.6.0",
  "prepublish": "PIP_USER=no python3 -m pip --disable-pip-version-check install -t ./pythonFiles/lib/python --no-cache-dir --implementation py --no-deps --upgrade -r requirements.txt && npm run package",
  "extensionFile": "ms-toolsai-jupyter-insiders.vsix"
}
Error: timeout after 5 mins
    at Timeout._onTimeout (/home/runner/work/publish-extensions/publish-extensions/publish-extensions.js:36:18)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Comment by petoknm** [comment]
What can we do about this:
 - can we speed up the build?
 - can we increase the build timeout?

**Comment by akosyakov** [comment]
was resolved
