### ISSUE TITLE
[emmanuelbeziat.vscode-great-icons] Error: Invalid URL in field 'repository': git+https://github.com/EmmanuelBeziat/vscode-great-icons.git

### ISSUE THREAD

**Issue by jankeromnes** [open-vsx/publish-extensions#39]
```
[FAIL] Could not process extension: {
  "id": "emmanuelbeziat.vscode-great-icons",
  "version": "2.1.48",
  "repository": "https://github.com/EmmanuelBeziat/vscode-great-icons"
}
Error: Invalid URL in field 'repository': git+https://github.com/EmmanuelBeziat/vscode-great-icons.git
    at Object.<anonymous> (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/publish.js:52:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/publish.js:14:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by jankeromnes** [comment]
Reported upstream as https://github.com/eclipse/openvsx/issues/128
