### ISSUE TITLE
[felixfbecker.php-debug][felixfbecker.php-intellisense] Error: Extension [...] version [...] is already published.

### ISSUE THREAD

**Issue by jankeromnes** [open-vsx/publish-extensions#4]
```
This extension consists of 465 files, out of which 392 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore
 DONE  Packaged: /tmp/tmp-2582V22KLzgxUb2L.vsix (465 files, 1.04MB)

[FAIL] Could not process extension: {
  "id": "felixfbecker.php-debug",
  "version": "1.13.0",
  "repository": "https://github.com/felixfbecker/vscode-php-debug",
  "checkout": "v1.13.0"
}
Error: Extension php-debug version 0.0.0-development is already published.
    at Object.<anonymous> (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/publish.js:52:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/publish.js:14:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

```
This extension consists of 227 files, out of which 101 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore
 DONE  Packaged: /tmp/tmp-2582mN3c1h3m0F7K.vsix (227 files, 319.9KB)

[FAIL] Could not process extension: {
  "id": "felixfbecker.php-intellisense",
  "version": "2.3.14",
  "repository": "https://github.com/felixfbecker/vscode-php-intellisense",
  "checkout": "v2.3.14"
}
Error: Extension php-intellisense version 1.5.4 is already published.
    at Object.<anonymous> (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/publish.js:52:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/publish.js:14:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by jankeromnes** [comment]
I think this is because the `"version"` in `package.json` are incorrect:

- https://github.com/felixfbecker/vscode-php-debug/blob/v1.13.0/package.json#L4 (expected: `"1.13.0"`, actual `"0.0.0-development"`)

- https://github.com/felixfbecker/vscode-php-intellisense/blob/v2.3.14/package.json#L10 (expected: `"2.3.14"`, actual `"1.5.4"`)

**Comment by spoenemann** [comment]
@felixfbecker is using [semantic-release-vsce](https://www.npmjs.com/package/semantic-release-vsce) for publishing. Maybe we need some equivalent for openvsx?
