### ISSUE TITLE
[formulahendry.auto-rename-tag] Error: @types/vscode ^1.44.0 greater than engines.vscode ^1.41.1. Consider upgrade engines.vscode or use an older @types/vscode version

### ISSUE THREAD

**Issue by jankeromnes** [open-vsx/publish-extensions#40]
```
[FAIL] Could not process extension: {
  "id": "formulahendry.auto-rename-tag",
  "version": "0.1.3",
  "repository": "https://github.com/formulahendry/vscode-auto-rename-tag",
  "location": "packages/extension"
}
Error: @types/vscode ^1.44.0 greater than engines.vscode ^1.41.1. Consider upgrade engines.vscode or use an older @types/vscode version
    at Object.validateVSCodeTypesCompatibility (/home/runner/work/publish-extensions/publish-extensions/node_modules/vsce/out/validation.js:85:19)
    at validateManifest (/home/runner/work/publish-extensions/publish-extensions/node_modules/vsce/out/package.js:550:22)
```

**Comment by filiptronicek** [comment]
I believe the only thing that can close this other than a fix from the author is to merge https://github.com/formulahendry/vscode-auto-rename-tag/pull/597.

**Comment by filiptronicek** [comment]
Since `0.1.10` is out [[1](https://open-vsx.org/extension/formulahendry/auto-rename-tag)], I believe this is no longer an issue.
