### ISSUE TITLE
[mtxr.sqltools] Error: SVGs are restricted in README.md; please use other file image formats, such as PNG: https://raw.githubusercontent.com/mtxr/vscode-sqltools/master/static/header-hero.svg?sanitize=true

### ISSUE THREAD

**Issue by jankeromnes** [open-vsx/publish-extensions#42]
```
[FAIL] Could not process extension: {
  "id": "mtxr.sqltools",
  "version": "0.22.7",
  "repository": "https://github.com/mtxr/vscode-sqltools",
  "checkout": "v0.22.7"
}
Error: SVGs are restricted in README.md; please use other file image formats, such as PNG: https://raw.githubusercontent.com/mtxr/vscode-sqltools/master/static/header-hero.svg?sanitize=true
    at Node.$.each (/home/runner/work/publish-extensions/publish-extensions/node_modules/vsce/out/package.js:362:27)
    at initialize.exports.each (/home/runner/work/publish-extensions/publish-extensions/node_modules/cheerio/lib/api/traversing.js:300:24)
    at ReadmeProcessor.<anonymous> (/home/runner/work/publish-extensions/publish-extensions/node_modules/vsce/out/package.js:352:22)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/publish-extensions/publish-extensions/node_modules/vsce/out/package.js:4:58)
```

**Comment by filiptronicek** [comment]
No longer an issue: https://github.com/mtxr/vscode-sqltools/blob/0c61f245d3afe0c7e89f8c39f3796b915005f93a/packages/extension/package.json#L63
