### ISSUE TITLE
Publishing "ms-azuretools.vscode-docker" fails

### ISSUE THREAD

**Issue by jankeromnes** [open-vsx/publish-extensions#5]
```
Executing prepublish script 'npm run vscode:prepublish'...
clean-webpack-plugin: /tmp/repository/dist has been removed.

⚠ ｢copy-webpack-plugin｣: unable to locate 'out/src/utils/getCoreNodeModule.js' at '/tmp/repository/out/src/utils/getCoreNodeModule.js'
> vscode-docker@1.0.0 vscode:prepublish /tmp/repository
> npm run webpack-prod


> vscode-docker@1.0.0 webpack-prod /tmp/repository
> gulp webpack-prod

[03:07:58] Requiring external module ts-node/register
[03:08:00] Using gulpfile /tmp/repository/gulpfile.ts
[03:08:00] Starting 'webpack-prod'...
External node modules: [ 'vscode-languageclient', 'opn' ]
Excluded node modules (external node modules plus dependencies) [
  'is-wsl',
  'opn',
  'semver',
  'vscode-jsonrpc',
  'vscode-languageclient',
  'vscode-languageserver-protocol',
  'vscode-languageserver-types'
]
   2544 modules

WARNING in ./node_modules/websocket/lib/BufferUtil.js
Module not found: Error: Can't resolve '../build/Release/bufferutil' in '/tmp/repository/node_modules/websocket/lib'

WARNING in ./node_modules/websocket/lib/Validation.js
Module not found: Error: Can't resolve '../build/Release/validation' in '/tmp/repository/node_modules/websocket/lib'

WARNING in ./node_modules/websocket/lib/BufferUtil.js
Module not found: Error: Can't resolve '../build/default/bufferutil' in '/tmp/repository/node_modules/websocket/lib'

WARNING in ./node_modules/websocket/lib/Validation.js
Module not found: Error: Can't resolve '../build/default/validation' in '/tmp/repository/node_modules/websocket/lib'

WARNING in ./node_modules/applicationinsights/out/AutoCollection/NativePerformance.js
Module not found: Error: Can't resolve 'applicationinsights-native-metrics' in '/tmp/repository/node_modules/applicationinsights/out/AutoCollection'

WARNING in unable to locate 'out/src/utils/getCoreNodeModule.js' at '/tmp/repository/out/src/utils/getCoreNodeModule.js'
[Error: ENOENT: no such file or directory, lstat '/tmp/repository/out/test'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/tmp/repository/out/test'
}
[03:09:28] Finished 'webpack-prod' after 1.45 min
 DONE  Packaged: /tmp/tmp-2582L0HTI0DwWrLq.vsix (185 files, 1.57MB)

[FAIL] Could not process extension: {
  "id": "ms-azuretools.vscode-docker",
  "version": "1.0.0",
  "repository": "https://github.com/microsoft/vscode-docker",
  "checkout": "v1.0.0"
}
Error: Cannot resolve dependency: vscode.docker
    at Object.<anonymous> (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/publish.js:52:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/publish.js:14:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by jankeromnes** [comment]
Likely a duplicate of #2.
