### ISSUE TITLE
Last update of Angular.ng-template extension (13.0.0) is bugged while extension from Visual Studio Code Marketplace is not

### ISSUE THREAD

**Issue by mlbiche** [open-vsx/publish-extensions#506]
OpenVSX just released yesterday the last update of the Angular.ng-template extension (version 13.0.0). This version seems to only bugged on OpenVSX. As the extension is published by open-vsx, I report the issue here but I don't know if it is the right place.

The Extension Host Log console logs the following issue :

```
[2021-11-19 10:43:16.646] [exthost] [error] Error: Cannot find module '/Users/***/.vscode-oss/extensions/angular.ng-template-13.0.0/dist/client/extension'
Require stack:
- /Applications/VSCodium.app/Contents/Resources/app/out/vs/loader.js
- /Applications/VSCodium.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/VSCodium.app/Contents/Resources/app/out/bootstrap-fork.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.n._load (/Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:28606)
    at Function.b._load (/Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:25193)
    at Function.h._load (/Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:60406)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Function.r [as __$__nodeRequire] (/Applications/VSCodium.app/Contents/Resources/app/out/vs/loader.js:5:101)
    at w._loadCommonJSModule (/Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:26603)
    at w._doActivateExtension (/Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:12894)
    at w._activateExtension (/Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:11867)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 1)
```

**Comment by akosyakov** [comment]
The publish job was fixed and it will do the right thing, but we need till the broken version is unpublished.

**Comment by hm2075** [comment]
who is responsible for this extension on open vsx?

![image](https://user-images.githubusercontent.com/53794682/143616427-c139240d-68f8-45c8-8fca-d55fceb1b701.png)


its been down for a number of days,

**Comment by akosyakov** [comment]
@filiptronicek @hm2075 Could you verify that it is resolved?

**Comment by akosyakov** [comment]
Hm, I just unpacked the latest version and still cannot see `dist` folder.

@filiptronicek could you make a priority to work on this issue please 🙏

**Comment by filiptronicek** [comment]
Although the build process is fixed, it looks like we first need to unpublish this version and somehow manually publish it from the build artefact.

**Comment by filiptronicek** [comment]
I just installed v13.1.0 from OpenVSX, it is working now. Closing the issue, we can open a new one if any further problems arise.

![image](https://user-images.githubusercontent.com/29888641/147267405-66d81068-8812-453a-ae0f-c651708a8f6f.png)
