### ISSUE TITLE
Publishing "ms-mssql.mssql" fails

### ISSUE THREAD

**Issue by jankeromnes** [open-vsx/publish-extensions#6]
```
This extension consists of 2451 files, out of which 2048 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore
 DONE  Packaged: /tmp/tmp-2582NWtlFKDrrFm5.vsix (2451 files, 2.8MB)

[FAIL] Could not process extension: {
  "id": "ms-mssql.mssql",
  "version": "1.9.0",
  "repository": "https://github.com/Microsoft/vscode-mssql"
}
Error: Cannot resolve dependency: vscode.sql
    at Object.<anonymous> (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/publish.js:52:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/publish.js:14:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by jankeromnes** [comment]
Likely a duplicate of #2.
