### ISSUE TITLE
golang.go is not updating

### ISSUE THREAD

**Issue by daenney** [open-vsx/publish-extensions#625]
The extension on OpenVSX is currently [0.34.1](https://github.com/golang/vscode-go/releases/tag/v0.34.1), released on the 30th of June (23 days ago).

In the mean time, 0.35.0 was released 5 days ago (18th of July), and 0.35.1 4 days ago (19th of July). Neither seem to have made it to OpenVSX. The respective releases on https://github.com/golang/vscode-go/releases each contain a `.vsix` artifact.

The upload of the extension is failing, but the Publish Extensions workflow is green, seemingly not propagating the failed status of a single extension to the workflow status:

```
golang.go: resolved https://github.com/golang/vscode-go/releases/download/v0.35.1/go-0.35.1.vsix from release
Processing extension: {
  "extension": {
    "id": "golang.go",
    "repository": "https://github.com/golang/vscode-go"
  },
  "context": {
    "msVersion": "0.35.1",
    "msLastUpdated": "2022-07-19T15:59:09.257Z",
    "msInstalls": 7386418,
    "msPublisher": "golang",
    "ovsxVersion": "0.34.1",
    "ovsxLastUpdated": "2022-07-01T04:12:24.835Z",
    "version": "0.35.1",
    "file": "/tmp/download/extension.vsix"
  }
}
[FAIL] Could not process extension: {
  "extension": {
    "id": "golang.go",
    "repository": "https://github.com/golang/vscode-go"
  },
  "context": {
    "msVersion": "0.35.1",
    "msLastUpdated": "2022-07-19T15:59:09.257Z",
    "msInstalls": 7386418,
    "msPublisher": "golang",
    "ovsxVersion": "0.34.1",
    "ovsxLastUpdated": "2022-07-01T04:12:24.835Z",
    "version": "0.35.1",
    "file": "/tmp/download/extension.vsix"
  }
}
Error: golang.go is dependent on , which have to be published to Open VSX first by their authors because of their licenses.
    at /home/runner/work/publish-extensions/publish-extensions/publish-extension.js:144:19
[FAIL] Could not process extension: {
  "extension": {
    "id": "golang.go",
    "repository": "https://github.com/golang/vscode-go"
  },
  "context": {
    "msVersion": "0.35.1",
    "msLastUpdated": "2022-07-19T15:59:09.257Z",
    "msInstalls": 7386418,
    "msPublisher": "golang",
    "ovsxVersion": "0.34.1",
    "ovsxLastUpdated": "2022-07-01T04:12:24.835Z",
    "version": "0.35.1",
    "file": "/tmp/download/extension.vsix"
  }
}
Error: failed with exit status: 255
    at ChildProcess.<anonymous> (/home/runner/work/publish-extensions/publish-extensions/publish-extensions.js:240:27)
    at ChildProcess.emit (events.js:400:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
```

```
Error: golang.go is dependent on , which have to be published to Open VSX first by their authors because of their licenses.
```

**Comment by filiptronicek** [comment]
Hi @daenney 👋, thanks for reporting this. I have looked into it and it was a Javascript thing I did not expect Javascript to do 😄 - https://github.com/open-vsx/publish-extensions/commit/6775ef26fe49caf5f43e5c39b0dc484a8060ba56

**Comment by daenney** [comment]
Brilliant, thank you so much!
