### ISSUE TITLE
[Equinusocio.vsc-material-theme] The engine "node" is incompatible with this module. Expected version ">=12". Got "10.21.0"

### ISSUE THREAD

**Issue by jankeromnes** [open-vsx/publish-extensions#73]
```
Attempting to publish Equinusocio.vsc-material-theme to Open VSX
Running: git clone --recurse-submodules https://github.com/material-theme/vsc-material-theme /tmp/repository
Running: yarn install
[FAIL] Could not process extension: {
  "id": "Equinusocio.vsc-material-theme",
  "repository": "https://github.com/material-theme/vsc-material-theme"
}
{ Error: Command failed: yarn install
error vsc-material-theme@32.8.0: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.21.0"
warning vsc-material-theme@32.8.0: The engine "vscode" appears to be invalid.
error Found incompatible module.
```

https://github.com/open-vsx/publish-extensions/runs/820891153?check_suite_focus=true

**Comment by jankeromnes** [comment]
Fixed! 🎉 

```
Processing extension: {
  "id": "Equinusocio.vsc-material-theme",
  "repository": "https://github.com/material-theme/vsc-material-theme"
}
Checking Open VSX version of Equinusocio.vsc-material-theme
Found version: 32.6.0
Attempting to publish Equinusocio.vsc-material-theme to Open VSX
Running: git clone --recurse-submodules https://github.com/material-theme/vsc-material-theme /tmp/repository
Running: yarn install
Creating Open VSX namespace failed -- assuming that it already exists
Error: Namespace already exists: Equinusocio
    at Object.<anonymous> (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/create-namespace.js:42:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/create-namespace.js:14:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 DONE  Packaged: /tmp/tmp-2957aNyEsCPU4atZ.vsix (52 files, 321.72KB)

🚀  Published Equinusocio.vsc-material-theme v32.8.0
```
