### ISSUE TITLE
[Equinusocio.vsc-material-theme] Error: Cannot resolve bundled extension

### ISSUE THREAD

**Issue by jankeromnes** [open-vsx/publish-extensions#8]
## Equinusocio.vsc-material-theme

```
DONE  Packaged: /tmp/tmp-3689UeBMh5aCwN47.vsix (52 files, 320.69KB)

[FAIL] Could not process extension: {
  "id": "Equinusocio.vsc-material-theme",
  "version": "32.5.0",
  "repository": "https://github.com/material-theme/vsc-material-theme"
}
Error: Cannot resolve bundled extension: equinusocio.vsc-community-material-theme
    at Object.<anonymous> (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/publish.js:52:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/publish.js:14:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Extension not found: Zignd.html-css-class-completion
```

**Comment by jankeromnes** [comment]
## vscjava.vscode-java-pack

```
 DONE  Packaged: /tmp/tmp-3402sE8LdQNv2Glm.vsix (16 files, 537.55KB)

[FAIL] Could not process extension: {
  "id": "vscjava.vscode-java-pack",
  "version": "0.8.1",
  "repository": "https://github.com/microsoft/vscode-java-pack"
}
Error: Cannot resolve bundled extension: VisualStudioExptTeam.vscodeintellicode
    at Object.<anonymous> (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/publish.js:52:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/publish.js:14:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by jankeromnes** [comment]
So, while extension `` is MIT license, it [depends on `VisualStudioExptTeam.vscodeintellicode`](https://github.com/microsoft/vscode-java-pack/blob/d59d860a6754a4cb991c5b5cd3f9961ff7484bbb/package.json#L143) which is itself not open source.

So let's remove `vscjava.vscode-java-pack` for now.

**Comment by jankeromnes** [comment]
Now failed with:

```
[FAIL] Could not process extension: {
  "id": "Equinusocio.vsc-material-theme",
  "version": "32.5.0",
  "repository": "https://github.com/material-theme/vsc-material-theme"
}
Error: Cannot resolve bundled extension: equinusocio.vsc-material-theme-icons
    at Object.<anonymous> (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/publish.js:52:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/publish.js:14:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
