### ISSUE TITLE
[Zignd.html-css-class-completion] Command failed: yarn run vscode:prepublish

### ISSUE THREAD

**Issue by jankeromnes** [open-vsx/publish-extensions#9]
```
Running: yarn install
🚀  Created namespace Zignd
Executing prepublish script 'yarn run vscode:prepublish'...
[FAIL] Could not process extension: {
  "id": "Zignd.html-css-class-completion",
  "version": "1.19.0",
  "repository": "https://github.com/Zignd/HTML-CSS-Class-Completion"
}
Error: Command failed: yarn run vscode:prepublish
warning html-css-class-completion@1.19.0: The engine "vscode" appears to be invalid.
error Command failed with exit code 2.

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:311:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 2,
  signal: null,
  cmd: 'yarn run vscode:prepublish'
}
```

**Comment by jankeromnes** [comment]
This works now:

```
 DONE  Packaged: /tmp/tmp-3402tiZcKQ3qP0UI.vsix (1982 files, 2.51MB)

🚀  Published Zignd.html-css-class-completion v1.19.0
[OK] Successfully published Zignd.html-css-class-completion to Open VSX!
```

Not sure what changed though.
